#!/bin/sh
# ----------------------------------------------------------------------------
#  Hvigor startup script, version 1.0.0
#
#  Required ENV vars:
# -------------------
#    NODE_HOME - location of a Node home dir with bin/node
#
#  Optional ENV vars:
# -------------------
#    HVIGOR_HOME - location of Hvigor home dir with bin/hvigor
# ----------------------------------------------------------------------------

# Resolve links: $0 may be a link
PRG="$0"
# Need this for relative symlinks.
while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=`dirname "$PRG"`"/$link"
    fi
done
SAVED="`pwd`"
cd "`dirname \"$PRG\"`/" >/dev/null
APP_HOME="`pwd -P`"
cd "$SAVED" >/dev/null

if [ -n "$NODE_HOME" ] ; then
    NODE_EXE="$NODE_HOME/bin/node"
else
    NODE_EXE="node"
fi

HVIGOR_HOME="$APP_HOME/.hvigor"

# Execute hvigor
exec "$NODE_EXE" "$HVIGOR_HOME/hvigor/hvigor.js" "$@"
